site_name: Higienizador de Ambulâncias
site_description: 'Projeto de PI2 - 2021/1'
site_author: 'Grupo 1'
docs_dir: docs/
repo_name: 'grupo1-pi2-2021-1/project-documentation'
repo_url: 'https://github.com/grupo1-pi2-2021-1/project-documentation'
nav:
    - Início: index.md
    - Ponto de Controle 1:
      - Termo de Abertura do Projeto: geral/docs/termo_abertura.md
      - Estrutura Analítica do Projeto: geral/docs/estrutura_analitica.md
    - Reuniões:
      - Sprint 0: geral/reunioes/sprint_0.md
    - Apresentações :
      - Ponto de Controle 1: geral/apresentacoes/ponto_controle_1.md
theme:
    name: material
    language: 'pt'
    palette:
      primary: 'teal'
      accent: 'teal'

repo_name: 'Higienizador de Ambulâncias'
repo_url: 'https://github.com/grupo1-pi2-2021-1/project-documentation/'
edit_uri: ''